import 'models/lesson_models.dart';

class MockLessonsRepository {
  static final List<Lesson> lessons = [
    const Lesson(
      lessonId: 'lesson_north_star',
      title: 'Finding Your North Star Metric',
      subtitle: 'Align product velocity with actual customer value creation.',
      domain: 'Product',
      estimatedMinutes: 4,
      cards: [
        TextInsightCard(
          id: 'ns_1',
          stepHeadline: 'The Vanity Trap',
          contentMarkdown:
              'Most startups track **vanity metrics**: registered accounts, page views, or total downloads.\n\nThese metrics go up and to the right even when the product is dying. A true **North Star Metric (NSM)** measures the moment your customer actually extracts value from your product.',
          keyTakeaway:
              'A good North Star Metric aligns product value, user retention, and revenue in a single number.',
        ),
        SwipePollCard(
          id: 'ns_2',
          stepHeadline: 'Intuition Check',
          statement:
              'Is "Daily Active Users (DAU)" an effective North Star Metric for an enterprise B2B accounting tool?',
          agreeFeedback:
              'Not quite! Accountants don’t want to spend more time inside software—they want tasks automated. An efficiency tool’s NSM should be "Reconciled accounts per minute", not time spent.',
          disagreeFeedback:
              'Exactly right! For productivity tools, higher time in-app often signals friction rather than value delivered.',
        ),
        MultipleChoiceCard(
          id: 'ns_3',
          stepHeadline: 'Case Application: Airbnb',
          question: 'What is Airbnb’s legendary North Star Metric?',
          options: [
            'Total app installs',
            'Nights booked',
            'Registered host listings',
            'Five-star host reviews',
          ],
          correctIndex: 1,
          explanation:
              '"Nights booked" captures value for both guests (finding accommodation) and hosts (earning rental income). All business flywheels flow directly from this single metric.',
        ),
        FillInBlankCard(
          id: 'ns_4',
          stepHeadline: 'Synthesis Exercise',
          sentenceBefore: 'For Spotify, the metric that best represents listener value is',
          blankExpected: 'Time Spent Listening',
          sentenceAfter: ', because it signals habitual retention over passive browsing.',
          wordBank: [
            'App Store Reviews',
            'Time Spent Listening',
            'Playlist Renames',
            'Total Search Queries',
          ],
          explanation:
              'Listening time reflects deep customer satisfaction, algorithmic recommendation accuracy, and subscription retention.',
        ),
        TextInsightCard(
          id: 'ns_5',
          stepHeadline: 'Executive Playbook',
          contentMarkdown:
              'To define your NSM this week:\n\n1. Identify the **"Aha! Moment"** when users feel delighted.\n2. Ensure it is **leading**, not lagging (Revenue is lagging; customer value is leading).\n3. Test if increasing it naturally lifts 30-day retention.\n\nBroadcast this number to every engineer and designer.',
          keyTakeaway:
              'Focus entire cross-functional sprints around driving your single North Star Metric.',
        ),
      ],
    ),
    const Lesson(
      lessonId: 'lesson_ltv_cac',
      title: 'Unit Economics: The 3:1 LTV:CAC Rule',
      subtitle: 'Diagnose startup cash burn before scaling marketing spend.',
      domain: 'Finance',
      estimatedMinutes: 5,
      cards: [
        TextInsightCard(
          id: 'ltv_1',
          stepHeadline: 'The Unit Economics Engine',
          contentMarkdown:
              'Before spending heavily on paid ads, you must verify your unit economics.\n\n- **CAC (Customer Acquisition Cost)**: Total sales & marketing spend divided by new customers acquired.\n- **LTV (Lifetime Value)**: Gross profit generated by a customer over their entire relationship.',
          keyTakeaway:
              'Scaling with negative unit economics is just setting investor money on fire faster.',
        ),
        MultipleChoiceCard(
          id: 'ltv_2',
          stepHeadline: 'Healthy SaaS Benchmarks',
          question: 'What is widely considered the golden ratio for LTV : CAC in healthy SaaS companies?',
          options: [
            '1 : 1 (Break-even)',
            '3 : 1 (Sustainable growth)',
            '10 : 1 (Always optimal)',
            '0.5 : 1 (Growth at all costs)',
          ],
          correctIndex: 1,
          explanation:
              'A 3:1 ratio provides enough margin to cover overhead, R&D, and reinvest into growth. Interestingly, a 10:1 ratio usually indicates you are under-investing in marketing and leaving market share to competitors!',
        ),
        FillInBlankCard(
          id: 'ltv_3',
          stepHeadline: 'Payback Period',
          sentenceBefore: 'Top venture-backed startups aim for a CAC payback period of under',
          blankExpected: '12 Months',
          sentenceAfter: ' to prevent severe cash flow insolvency during rapid expansion.',
          wordBank: ['36 Months', '12 Months', '48 Hours', '5 Years'],
          explanation:
              'Recovering CAC within 12 months allows a company to recycle capital within the same fiscal year without raising dilutive emergency bridge rounds.',
        ),
        TextInsightCard(
          id: 'ltv_4',
          stepHeadline: 'Action Checklist',
          contentMarkdown:
              '### 3 Levers to Fix Bad Ratios:\n\n1. **Expand Gross Margin**: Reduce cloud hosting costs or service delivery overhead.\n2. **Reduce Churn**: Keeping existing users lifts LTV without increasing CAC.\n3. **Upsell Existing Accounts**: Net Revenue Retention (NRR) > 120% makes LTV skyrocket.',
          keyTakeaway: 'Retention is the highest leverage input to Lifetime Value.',
        ),
      ],
    ),
  ];
}
